### PR TITLE
Add numeric sorting option

### PR DESCRIPTION
**Pull request by airdrummingfool**
This PR is my first attempt at #39 (feedback welcome!).  A couple notes:

- If neither argument can be parsed into a number, they are left as strings, which allows any string entries in the list to be sorted among themselves.
- If only one of the arguments cannot be parsed into a number, it is assigned `undefined`. This is to make sure the non-numeric entries drop to the bottom of the sorted list; otherwise the comparisons fail and string entries could end up in the middle of numeric ones (comparing a string to a number always returns `0`, because `string < number` and `string > number` both return `false`).
- In https://github.com/thomasloven/lovelace-auto-entities/issues/39#issuecomment-554385809 you mentioned making `ignore_case` incompatible with this option, but since this supports sorting strings in the same list, I think it should be allowed to be used at the same time.

### CODE REVIEW

**Comment by airdrummingfool** [comment]
I've merged with master and rebuilt `auto-entities.js` to fix merge commits that popped up.

**Comment by thomasloven** [comment]
I'd prefer having it added as a new case in the `switch(method.method)` with the rest of the methods, and keep just globaly applied "tweaks" in `compare`.

**Comment by thomasloven** [comment]
Regarding the comment about making sure `ignore_case` was not set, I had forgotten here was already a check in place for that. I was afraid `compare` would try to run `.toLowerCase` on numbers otherwise.

**Comment by airdrummingfool** [comment]
@thomasloven I'd consider this a (sorta) globally-applied tweak, since it can apply to comparing both `state` and `attribute` (and, arguably, `name`/`friendly_name`).  It seems like moving to the `switch` would limit it to only comparing based on `state`.

I view this feature as comparable to `ignore_case` that would apply no matter what method was selected (granted, it would definitely not be useful to sort `domain` or `entity_id` numerically).

**Comment by thomasloven** [comment]
Ah, yes! You are right.

**Comment by thomasloven** [comment]
I've merged this manually, because github wouldn't let me.
Thanks a lot!

**Pull request closed without merging**
