### PR TITLE
Add ability to filter by custom time attributes

### LINKED ISSUE #78: How to compare to date or timestamp attribute
Hello,
zigbee2mqtt provides a `last_seen` attribute, formatted either as a date (`2020-01-20T06:31:08.678Z`) or an epoch timestamp (`1579502698`). I'd like to show all devices that haven't been seen in the past 24 hours based on this attribute (`last_updated` gets changed whenever z2m or HA restarts) - is there a way to do this?

Thanks for this awesome project!

### PR DESCRIPTION
**Pull request by igoree**
This pull request adds a simple syntax to filter entities by custom time attributes. This syntax is also supported (but not required for backward compatibility) in `last_updated`, `last_changed` and `last_triggered` filters. For example:

```yaml
filter:
  include:
    - attributes:
        last_seen: "> 1h ago" # Entity was seen more than 1 hour ago
    - last_updated: "< 20m ago" # Entity was updated less than 20 minutes ago
    - last_triggered: "> 1d ago" # Entity was triggered more than 1 day ago
    - last_changed: "< 10" # Entity was changed less than 10 minutes ago. Still works for the predefined time filters but doesn't work for custom attributes
```

Closes #78

### CODE REVIEW

**Comment by palfrey** [comment]
Does this support "before now" operations? I'm looking at data from https://github.com/pnbruckner/ha-sun2 and interested in just getting the future events

**Comment by igoree** [comment]
To get only future events you can use '< 0m ago'. It looks weird but works. You can use negative numbers to set a more specific offset. I think future events need a special syntax but I have not planned on adding it.

**Comment by bjeanes** [comment]
I'd also love to see this. My use-case is I have my on-call schedule from work loaded with [`ics_calendar`](https://github.com/franc6/ics_calendar) and it has attributes like:

```yaml
message: bjeanes is on call
all_day: false
start_time: 2022-03-18 10:30:00
end_time: 2022-03-21 10:30:00
location: null
description: null
offset_reached: false
friendly_name: On-call
```
 
I'd like to be able to show this in a list of "Important" items (along with low batteries, fire warnings, etc) some minimum threshold before `start_time`. I know I can work around this with a template sensor but I do think having time comparison in auto-entities would be preferable and very versatile.

@thomasloven is this PR something you'd consider?

**Comment by lorond** [comment]
`template` could be a workaround. Here is an example of unavailable entities or entities last seen more then 8 hours ago:

```
  - type: custom:auto-entities
    show_empty: true
    card:
      type: entities
      title: Unavailable
      show_header_toggle: false
    filter:
      include:
        - state: unavailable
      template: |
        {% for s in states.sensor if s.entity_id.endswith('_last_seen') and s.state|as_datetime < (now() - timedelta(hours=8)) %}
          {{ s.entity_id }},
        {% endfor %}
```

**Comment by thomasloven** [comment]
I like it. Thanks!

**Comment by thomasloven** [comment]
Merged outside of github.

**Comment by arrelid** [comment]
@thomasloven @igoree I've been trying to wrap my head around this for some time now, but can't seem to get this to work.

I got a couple of `input_datetime` entities that all have a corresponding timestamp attribute, e.g. `timestamp: 1696802400`. To show all such entities where the timestamp is >9 days ago, I thought I'd do:

```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - attributes:
        timestamp: "> 9d ago"
```

(yes, I'm asking for all entities, but one could easily add a domain filter later)

For some reason, this just list _all_ entities with a timestamp attribute. If I flip the condition (less than 9 days), I get an empty list. What am I missing?

**Pull request merged**
