### PR TITLE
add ability to filter by entity platform

### PR DESCRIPTION
**Pull request by Max101**
Hi, I tested this small fix and it allows for filtering by entity platform and should solve #181

Example usage:
```
type: custom:auto-entities
show_empty: false
card:
  type: entities
  title: F0 Lights
  state_color: true
filter:
  include:
    - domain: light
      platform: knx
  exclude:
    - state: unavailable

### CODE REVIEW

**Comment by Csontikka** [comment]
please merge it!

**Comment by thomasloven** [comment]
Thanks a lot!
I decided to call this `integration` instead since that's closer to the reality.
It's included in 1.10.0

**Comment by ristomatti** [comment]
@thomasloven I thought PR's are pretty much never merged on this repository and wondered why anyone bothers to contribute. Apparently that is not the case but contributors [rarely seem to get credit](https://github.com/thomasloven/lovelace-auto-entities/graphs/contributors). I doubt this is on purpose from your side but it does not give a very encouraging image.

Anyway, In case you had not thought about this - in order for a contributor to get credited on the repo stats, what you can do is for example pull the changes to a local branch, then amend the commit. This still retains the PR creator's email which in turn will show up in the stats and as a "Contributor" badge on repo isssue/PR comments. Of course, a more traditional approach would be to ask for the contributor to do the wished changes but it does take more time and I've very much noticed you've got a ton of code to maintain.

**Comment by thomasloven** [comment]
It really isn't on purpose, and I'm honestly very sorry it does end up this way.

I have... bouts of inspiration, where I pull up a project and starts working on it, implementing stuff I've been thinking about for a while or heard of some time ago. When I'm nearing a release, I go to the github issues and start checking stuff off, sometimes adding more things, and finally I go to the PRs and do the same thing.
At that point there's usually all kinds of conflicts with my local working copy, and often - such as in this case - I have already implemented the functionality without even noticing the PR was there.

I know I should do it differently, but at the risk of sounding pretentions I'm suffering from success. I get more PRs and issues across my repos than I can handle continuously with my curent IRL work load (this is a hobby and I wish it to remain that way), and starting from the other end - checking the PRs first - I fear would overwhelm me when I haven't been working with the code base recently, and risk putting me off development alltogether.

Again, I really am truly sorry things end up this way and I do appreciate the effort people put in immensely.

**Comment by ristomatti** [comment]
@thomasloven I think I know exactly what you're talking about with the bouts of inspiration as that is how all my off work projects end up happening....

You've created irreplaceable tools for the HA ecosystem, which in ny case likely were the tipping point for me to end up staying after trying HA (the default dashboard is too limited!). In the end, people will definitely appreciate more if you push more updates than small technicalities kine this one.

 In the long run I do believe taking the time to try "fix" this pattern might be a good idea. As with most open source side projects, you might lose the interest or lack the time to maintain all these valuable tools. In that situation it might be comforting to notice there's one or two trusted contributors who are willing to continue maintaining the projects!

The PR notification issue is an oddball. At least when quickly skimming (on mobile), I didn't find such setting from my own repos or the profile settings. Maybe you've got so many of them, your email provider/client has started marking them as spam? 😬

**Pull request closed without merging**
